"$schema" = 'https://starship.rs/config-schema.json'

[package]
disabled = true

[python]
disabled = true

[gcloud]
disabled = true

[nodejs]
disabled = true

[battery]
disabled = true

[netns]
disabled = true

[git_status]
style = 'bold green'
ahead = '[â‡¡$count](green)'
behind = '[â‡£$count](red)'
diverged = '[â‡¡$ahead_count](green)[â‡£$behind_count](red)'
staged = '[+$count](green)'
stashed = '[ğŸ’°$count](cyan)'
modified = '[!$count](red)'
untracked = '[?$count](blue)'
deleted = '[-$count](red)'
